import { TEXT_NODE_TYPE_NAME, VNode } from "./index";

// TODO : Move VNode type and VNode constants here (TEXT_NODE_TYPE_NAME)

// NOTE : Keep it in a function and do not inline this
// It seems to be V8 optimized. @see Preact source code
export function createVNode ( type, props, key?, ref? ):VNode {
	return { type, props, key, ref }
}

export function cloneVNode ( vnode:VNode ) {
	return {
		...vnode,
		// IMPORTANT : also clone props object
		props: { ...vnode.props }
	}
}

export function h ( type, props, ...children ) {
	// Remove debug properties
	// FIXME : Keep them in debug mode ? But in vnode not in props.
	delete props.__self
	delete props.__source
	// Extract key and ref from props
	const { key, ref, ...nodeProps } = props
	// Inject children in props
	nodeProps.children = ( children ?? [] ).map( child => (
		// Convert string and number children to text virtual nodes
		( ["string", "number"].indexOf( typeof child ) !== -1 )
		? createVNode( TEXT_NODE_TYPE_NAME, { value: child + '' })
		// Otherwise keep child generated by JSX
		: child
	))
	return createVNode( type, nodeProps, key, ref )
}
